### ISSUE TITLE
Kafka invocations don't support workflow auxiliary handlers

### ISSUE THREAD

**Issue by StephanEwen** [restatedev/restate#2100]
Workflows can be triggered from Kafka events, meaning the `run` handler can be invoked.

But auxiliary handlers, for example for signals, cannot be invoked from Kafka. Trying to set up a subscription yields:
```
{"message":"[META0009] invalid sink URI 'service://createUser/approve': shared handlers cannot be used as sinks.","restate_code":"META0009"}

```

**Comment by slinkydeveloper** [comment]
The reason I initially forbid it is that it's unclear what the ordering semantics should really be, vs what is the user expectation. Do you expect to receive messages in order? Or do you expect max-fanout (like services behave now)? I personally found this confusing, because we tell people that virtual objects/workflows receive kafka messages in order.

There's this issue where I also wrote some comments about our ordering delivery semantics a while ago https://github.com/restatedev/restate/issues/1423

**Comment by StephanEwen** [comment]
Is the confusion about
 topic1 -> run()
 topic2 -> approve()

and topic2 messages (approval) can overtake topic1 and thus be lost (no matching workflow active)?

**Comment by slinkydeveloper** [comment]
no, this has nothing to do with multiple topics. Shared handlers can be invoked in parallel, because they don't take the exclusive lock (not for virtual objects, and neither for workflows).

So If you get two messages with same key on the same topic, the shared handler will handle those in parallel, rather than handling them one at the time (which is what virtual object exclusive handlers and workflow handlers would do instead).

**Comment by StephanEwen** [comment]
I see where you are coming from, but then again, same is true for RPCs on shared handlers. Can overtake, execute in parallel, etc.
Not sure I see this as a blocker.

The standard workaround where you send the kafka event to a service and then call the shared handler has the same behavior. Even when the event lands on an object, unless you use a sync call from object to handler.
