### ISSUE TITLE
Uploading state snapshots to an object store

### ISSUE THREAD

**Issue by tillrohrmann** [restatedev/restate#2197]
Ideally, we support a wide range of different object stores and filesystems. That way users can run Restate also w/o an object store. Moreover, the upload process should happen in the background.

Libraries to look at could be: https://crates.io/crates/opendal and https://crates.io/crates/object_store.
```[tasklist]
### Tasks
```

**Comment by Xuanwo** [comment]
As mentioned in https://github.com/restatedev/restate/issues/1882#issuecomment-2431663048, please let me know if there's anything we can do from the opendal side.

**Comment by pcholakov** [comment]
Hey @Xuanwo, I unfortunately only just saw your comment yesterday. We evaluated OpenDAL and decided to go with `object_store` for the first iteration of our snapshotting integration because of its narrower focus. Our requirements are very simple at the moment (just GET and multi-part PUT against a handful of services for the foreseeable future), but thanks very much for getting in touch and we'll certainly keep re-evaluating this as our needs evolve!
