### ISSUE TITLE
Restrict key to String type in keyed services

### ISSUE THREAD

**Issue by AhmedSoliman** [restatedev/restate#955]
We don't need composite types in keyes. A String is sufficient for over 90% of cases and composite keys introduce an accidental cross-cutting complexity to the system.

The changes we can do to:
- Metas to validate that the key option is set on a String.
- The key string has size limit (update the docs). A provisional size limit is 128c. We should fail calling/creating service instances with longer keys and if the string is not a valid utf8.
- Remove the poly-type-view for service key in datafusion.

**Comment by slinkydeveloper** [comment]
@AhmedSoliman do you think restricting the size is something we should do now? Is the key size a problem now?

**Comment by slinkydeveloper** [comment]
For the time being I will not restrict the key size, as I'm not aware of any specific problem with the key size. This adds some non-trivial friction for the user, because it introduces another "reason" for the key extraction to fail, thus increasing the chance of getting an invocation stuck on a resolution error for a call/background call. Because we still don't have good solutions atm to deal with those issues, it would be better to reduce chances of getting stuck in those situations.

**Comment by slinkydeveloper** [comment]
Done

**Comment by AhmedSoliman** [comment]
Service keys will be visible in CLIs and other tools when visualizing service occupancy and status, an unbounded service key makes designing UIs a lot harder.
